[feat]: #9 알림뷰(NoticeView) UI 구현
DeveloperAcademy-POSTECH/MC3-Team17-Hou pull request #18
Opened 2022-07-18 16:53 UTC by PecanPiePOS

# Issue Number
#9 알림뷰 UI

⭐️주의 : 현재 @main이 (처음 시작하는 뷰) 저의 파일의 맞춰 Notice 로 되어 있습니다.

## Changed Files
- Ninano/Ninano.xcodeproj/project.pbxproj
- Ninano/Ninano/.swiftlint.yml
- Ninano/Ninano/Assets.xcassets/AppIcon.appiconset/Contents.json
- Ninano/Ninano/Info.plist
- Ninano/Ninano/Notice/InterestLisViewController.swift
- Ninano/Ninano/Notice/KeywordTableViewCell.swift
- Ninano/Ninano/Notice/KeywordViewController.swift
- Ninano/Ninano/Notice/LineSegmentedControl.swift
- Ninano/Ninano/Notice/Notice.storyboard
- Ninano/Ninano/Notice/NoticeGridCollectionViewCell.swift
- Ninano/Ninano/Notice/NoticeViewController.swift
 
## Pull Request 내용 (변경 및 추가된 사항들)

- Keyword View(키워드뷰) 완성
- InterestList View(관심 목록 뷰) 완성
- 버튼 UI 완성 (Alert 포함)
- Segmented Control Custom 완성

## References (Optional)

- Segmented Controller 사용해서 뷰 만들고 바꾸기
https://stackoverflow.com/questions/43512442/switch-the-sub-viewcontroller-use-segmented-control
https://spin.atomicobject.com/2015/09/02/switch-container-views/

- ScrollView Constraint Issue 해결 - (따라하다가 반쯤에서 고침 그래서 확실하진 않음)
https://corykim0829.github.io/ios/UIScrollView-with-storyboard/#

- [Error] unrecognized selector sent to instance
https://yeniful.tistory.com/51

- TableViewCell 관련
https://velog.io/@wook4506/iOS-Swift-TableView-Cell-%EC%BB%A4%EC%8A%A4%ED%84%B0%EB%A7%88%EC%9D%B4%EC%A7%95
https://lucidmaj7.tistory.com/290
(동적 높이 커스텀)
https://velog.io/@tnddls2ek/TableView-%EB%8F%99%EC%A0%81%EC%9D%B8-%EC%85%80-%EB%86%92%EC%9D%B4-%EC%A1%B0%EC%A0%88
(섹션)
https://lucidmaj7.tistory.com/292?category=734921

- CollectionView 에 Grid 형식으로 만들기
https://sunidev.tistory.com/4

- 버튼에 Alert 기능 구현하기
https://leeari95.tistory.com/53

- Custom Segmented Control UI 구현
https://www.lpktechnosoft.com/blog-single-image-post/36/super-easy-switch-tab-using-uisegmented-control-in-swift-5

## Checklist

- [ ] merge할 branch를 확인했나요?
- [ ] coding conventions을 지켰나요?
- [ ] 이 PR에 관계없는 변경사항들이 없나요?
- [ ] PR 날리는 코드를 self 리뷰 했나요?

2022-07-19 02:25 UTC, Asher3576 approved these changes
수고하셨습니다~~ PP 역시 WWDC 위너 답게 멋집니다!!

2022-07-19 02:25 UTC, Asher3576 commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +        self.segmentedControl.frame = CGRect(x: self.segmentedControl.frame.minX, y: self.segmentedControl.frame.minY, width: segmentedControl.frame.width, height: 25)
✅ 
한 줄에 너무 많은 글자가 들어가면 읽기 어려워서 행을 나누어주면 좋을 것 같아요!

2022-07-19 02:25 UTC, Asher3576 commented on Ninano/Ninano/Notice/InterestLisViewController.swift
> +        return cell!
✅
전체적인 코드의 개행 통일성을 맞춰 주셔도 좋을거 같아요~🫡

2022-07-19 02:43 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/InterestLisViewController.swift
> +        return cell!
수정하겠슴다~!

2022-07-19 03:36 UTC, unnnyong commented on Ninano/Ninano.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 98TYR8WM82;
Team이 수정되어도 괜찮나요 ? merge후 다른 팀원의 branch에서 conflict가 발생되지 않을까 우려되네요.

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/InterestLisViewController.swift
> +class InterestLisViewController: UIViewController {
```suggestion
final class InterestLisViewController: UIViewController {
```

더이상 상속되지 않는 것을 의미하는 final을 붙이는게 좋아보여요 ~

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/InterestLisViewController.swift
> +    @IBOutlet weak var interestCollectionView: UICollectionView!
추후 사용될 예정인가요 ?

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/InterestLisViewController.swift
> +    let gridImage = ["camera.macro.circle", "camera.macro.circle.fill", "sun.dust.fill", "cloud.moon.bolt", "hurricane", "wrench", "radio.fill"]
```swift
enum GridImage: String, CaseIterable {
    case cameraLine = "camera.macro.circle"
    // ....

    var title: String { self.rawValue }
}



label.title = gridImage.camerawLine.title
```

enum으로 관리해서, caseiterable로 설정하면 혹시 발생할 오타를 줄일 수도 있고 String보다 유지보수에도 쉬워보여요 !

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/KeywordTableViewCell.swift
> +    @IBOutlet weak var keywordImage: UIImageView!
```suggestion
    @IBOutlet private weak var keywordDate: UILabel!
    @IBOutlet private weak var keywordAlarmTitle: UILabel!
    @IBOutlet private weak var keywordTitle: UILabel!
    @IBOutlet private weak var keywordImage: UIImageView!
```

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/KeywordTableViewCell.swift
> +class KeywordTableViewCell: UITableViewCell {
```suggestion
final class KeywordTableViewCell: UITableViewCell {
```

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/KeywordTableViewCell.swift
> +    }
지금 컴파일되는건 낭비... 이지 않을까 싶어서요, 사용될 때 추가하는건 어떤가요 ?

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/KeywordViewController.swift
> +        return cell!
!는 지양되어야합니다.

https://github.com/DeveloperAcademy-POSTECH/MC3-Team17-Hou/pull/18/files#diff-b8f3cc0ac5e3a9e494f7d9b130aa9995bf1c5d8db48916bcc4a87e7a4e9df59bR38 에서 guard let으로 선언하면 방지 가능해보여요

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/LineSegmentedControl.swift
> +class LineSegmentedControl: UISegmentedControl {
어떤 용도의 class인가요 ? 👀

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/LineSegmentedControl.swift
> +extension UIImage {
extension은 `UIImage+.swift`와 같은 별도의 파일에서 관리하는것이 통일성에도 좋아보입니다 ~

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/LineSegmentedControl.swift
> +    class func getSegRect(color: CGColor, andSize size: CGSize) -> UIImage {
class method여야하는 이유가 있을까요 ?

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/LineSegmentedControl.swift
> +        return rectangleImage!
! 의 개선이 필요해보여요 ~

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +            // completion: 해당 alert 가 성공적으로 수행되고 나서 이 함수가 끝난 뒤 뭘 할거냐? 라고 지정해주는 부분 이것도 closure 로 빼자.
```suggestion
            // TODO: completion: 해당 alert 가 성공적으로 수행되고 나서 이 함수가 끝난 뒤 뭘 할거냐? 라고 지정해주는 부분 이것도 closure 로 빼자. 
```

TODO일까요 ?

2022-07-19 03:45 UTC, unnnyong commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +    @IBAction func noticeOutTapped(_ sender: UIButton) {
`didTappedButton` 과 같이 IBAction도 method이기때문에 메소드의 어두는 동사로 시작되는것이 좋습니다 ~

2022-07-19 04:57 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/KeywordTableViewCell.swift
> +class KeywordTableViewCell: UITableViewCell {
넵 알겠습니다 감사합니다!

2022-07-19 04:57 UTC, PecanPiePOS commented on Ninano/Ninano.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 98TYR8WM82;
이건 따로 수정하겠습니다!

2022-07-19 04:57 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/KeywordTableViewCell.swift
> +    @IBOutlet weak var keywordImage: UIImageView!
감사합니다! private 을 항상 고려해야겠네요...

2022-07-19 04:57 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +            // completion: 해당 alert 가 성공적으로 수행되고 나서 이 함수가 끝난 뒤 뭘 할거냐? 라고 지정해주는 부분 이것도 closure 로 빼자.
네 맞습니다. TODO 를 안 써봤는데 찾아보고 잘 써보겠습니다 감사합니다!

2022-07-19 04:57 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +        self.segmentedControl.frame = CGRect(x: self.segmentedControl.frame.minX, y: self.segmentedControl.frame.minY, width: segmentedControl.frame.width, height: 25)
네엡 알겠습니다 감사합니다!

2022-07-19 06:09 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/LineSegmentedControl.swift
> +extension UIImage {
감사합니다 영 ! 그런데 궁금한게... 그러면  UIImage 나 UISegmentedControl 등에 대해 extension 을 하면 따로따로 다 만들어야하나요 아니면 특정 extension 파일 하나로 다 묶어 놓는게 좋을까요?

2022-07-19 06:09 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/LineSegmentedControl.swift
> +class LineSegmentedControl: UISegmentedControl {
Segmented Control Custom 을 위해 사용된 클래스인데, 저도 정확히는 어떤 의도 인지는 모르겠습니다...
UISegmentedControl extension 에서 기능을 추가하고 Identifier 를 추가해서 따로 쓰려고 만든 건지... 
저도 잘 모르겠습니다ㅎㅎ..ㅜ 저도 처음에 이거 뭔데 비어있지..? 이랬는데 일단 작동은 잘 하니깐 뒀습니다

2022-07-19 06:35 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/KeywordTableViewCell.swift
> +    }
넵 주석처리 해놓겠습니다!

2022-07-19 07:56 UTC, rriver2 requested changes
역시 PP.. segmented control... 구현하신 거 대단하네요 ! 

폴더링을 잘해주셔서 코드가 잘 나눠져 있어서 코드리뷰하기 편했던거 같아요 ><
didChangeIndex() 함수에서 switch로 button을 분기처리한게 인상 깊었습니다

첫 Hou의 PR 추카포카 합니다 ~~ 호우!!!

2022-07-19 07:56 UTC, rriver2 commented on Ninano/Ninano/Notice/InterestListViewController.swift
> +    }
저는 너무 많은 줄 띄어쓰기는 가독성이 안 좋은 것 같아요
최소한으로 개행을 쓰는 게 어떨까 하는 저의 생각입니다 ! 다른 분들의 의견도 궁금합니다 !

@unnnyong 개행을 하는데에 좀 더 정확한 척도나 기본적으로 사람들이 주로 쓰는 개행 규칙이 있나요 ?

2022-07-19 07:56 UTC, rriver2 commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +
"목록 전체 삭제" 누를 시에 런타임 에러가 발생하는데 확인부탁드립니다..
<img width="1512" alt="스크린샷 2022-07-19 오후 4 52 50" src="https://user-images.githubusercontent.com/82457928/179697259-00beabee-27ae-4045-bac3-477c2e870e1c.png">

2022-07-20 00:26 UTC, PecanPiePOS commented on Ninano/Ninano/Notice/NoticeViewController.swift
> +
고쳣읍니당 감삼다

2022-07-20 00:31 UTC, rriver2 approved these changes
피파파 고생하셨습니다 >< !!!

2022-07-20 00:31 UTC, lee02029 approved these changes

2022-07-20 00:34 UTC, merged